server:
  port: 9999
  context-path: /gxkygl
spring:
  datasource:
      username: root
      password: 12565276
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql:///gxkygl?useUnicode=true&characterEncoding=utf8
  application:
    name: gxkygl-service
  jpa:
    generate-ddl: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  thymeleaf:
    cache: false
    cache-period: 0
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  aop:
    auto: true
    proxy-target-class: true
logging:
  level:
    com:
      mryao: DEBUG